
* Notes

I installed:
sudo apt install nodejs
sudo apt install npm

I ran,
npm init
to get myself a package.json file.

Then, I ran
npm install

to install the packages and save to package.json file:
npm install express --save

Then, I ran this:
npm install morgan
npm install compression
npm install body-parser
npm install method-override

npm install ejs

You could also just modify the package.json file, then type "npm update".

npm install express-sessions

Then, I installed this:
sudo apt-get install mongodb

This may be in conflict with the official mongodb repo:
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

Read:
IMPORTANT
The mongodb package provided by Ubuntu is not maintained by MongoDB Inc. and conflicts with 
the official mongodb-org package. If you have already installed the mongodb package on your 
Ubuntu system, you must first uninstall the mongodb package before proceeding with these 
instructions.


You run with, "node server"

Go to this website:
http://localhost:3000/users
to check the database.

Go to a specific id with:
http://localhost:3000/users/[id]

where [id] is the user id value.

Add to database with this commandline option:
curl -X POST -H "Content-Type: application/json" -d '{"firstName":"First", "lastName":"Last","email":"user@example.com","username":"username","password":"password"}' localhost:3000/users

To update a specicfic entry:
curl -X PUT -H "Content-Type: application/json" -d '{"lastName":"Updated"}' localhost:3000/users/[id]

curl -X PUT -H "Content-Type: application/json" -d '{"lastName":"Updated"}' localhost:3000/users/5fad92ad04b22626c8f30551
